spring:
  application:
    name: eureka-server #指定服务名称


server:
  port: 8761

eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

#这部分被peer1和peer2共享，如果peer1有对应配置，则会覆盖这里的配置
management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  #  注意有没有s
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  config:
    activate:
      on-profile: peer1 # 指定profile=peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名是peer1
    home-page-url: eureka
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/  #设置服务注册中心的URL，将自己注册到peer2这个Eureka上面去，对应register-with-eureka

---

spring:
  config:
    activate:
      on-profile: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
