server:
  port: 8080
spring:
  application:
    name: config-server
  #云配置中心
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo.git # Git仓库地址
          repos:
            simple: https://git.oschina.net/itmuch/spring-cloud-config-repo.git
            special:
              pattern: special*/dev*,*special*/dev*
              uri: https://git.oschina.net/itmuch/spring-cloud-config-repo.git


logging:
  level:
    org.springframework.cloud: debug # 通过debug，我们可以看到根目录在（o.s.boot.SpringApplication started by xxxxx in C:\Users\xxxxx\IdeaProjects\mallcloud)



